image: node:latest

cache:
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

before_script:
  - npm set progress=false

building:
  stage: build
  variables:
    NODE_ENV: "development"
  script:
    - npm i --no-optional
    - npm run build
  type: build
  tags:
    - npm
    - node
  only:
    - tags
    - master

testing:
  stage: test
  # services:
  #   - mongo:3.2
  #   - rabbitmq:3.6
  #   - redis:3.2
  variables:
    NODE_ENV: "development"
  script:
    - npm i --no-optional
    - npm run test
  type: test
  tags:
    - npm
    - node
  only:
    - tags
    - master

staging:
  stage: deploy
  environment: staging
  variables:
    NODE_ENV: "production"
  script:
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    # Add the SSH key stored in SSH_RUNNER_KEY variable to the agent store
    - ssh-add <(echo "$SSH_RUNNER_KEY")
    # For Docker builds disable host key checking. Be aware that by adding that
    # you are suspectible to man-in-the-middle attacks.
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Install pm2
    - npm i pm2 -g
    # Deploy project
    - pm2 deploy ecosystem.json staging
  type: deploy
  tags:
    - npm
    - node
  only:
    - master
